language: c

dist: trusty

before_install: ./travis-install.sh

script: travis_wait 60 ./travis-build.sh

sudo: required

git:
  depth: 2147483647

env:
  global:
    - SLEEP_A_BIT="sleep 0.2"
    - VERBOSE="1"

matrix:
  include:
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=memcheck
        - VALGRIND_TESTDIR=tests
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=helgrind
        - VALGRIND_TESTDIR=tests
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=drd
        - VALGRIND_TESTDIR=tests
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=memcheck
        - VALGRIND_TESTDIR=tests-m32
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=helgrind
        - VALGRIND_TESTDIR=tests-m32
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=drd
        - VALGRIND_TESTDIR=tests-m32
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=memcheck
        - VALGRIND_TESTDIR=tests-mx32
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=helgrind
        - VALGRIND_TESTDIR=tests-mx32
    - compiler: gcc
      env:
        - TARGET=x86_64
        - CHECK=valgrind
        - TIMEOUT_DURATION=1200
        - VALGRIND_TOOLS=drd
        - VALGRIND_TESTDIR=tests-mx32
